version: "3.9"
services:
  kurasmart-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/kura_db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kura_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
