"""Add description to Candidate

Revision ID: 03cf80a03279
Revises: e54a43165219
Create Date: 2025-06-12 12:47:47.969802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cf80a03279'
down_revision = 'e54a43165219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('party_name')
        batch_op.drop_column('position')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('party_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
