"""Add description to Candidate

Revision ID: 2c259bc25d0d
Revises: 03cf80a03279
Create Date: 2025-06-12 12:59:25.703101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c259bc25d0d'
down_revision = '03cf80a03279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('party_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('party_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
