"""Make candidate.position nullable

Revision ID: 311afb43435a
Revises: 30efe22869d9
Create Date: 2025-07-04 11:03:12.184611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311afb43435a'
down_revision = '30efe22869d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
