"""Add position_id to Candidate

Revision ID: 84fc0642fd82
Revises: 2c259bc25d0d
Create Date: 2025-06-16 16:20:15.390059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fc0642fd82'
down_revision = '2c259bc25d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'position', ['position_id'], ['id'])

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uix_voter_election_position', ['voter_id', 'election_id', 'position_id'])
        batch_op.create_foreign_key(None, 'position', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_voter_election_position', type_='unique')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    op.drop_table('position')
    # ### end Alembic commands ###
