"""Rebuild candidate table with unique constraint

Revision ID: 863df0368456
Revises: 2fc023282ae9
Create Date: 2025-06-24 10:20:44.357548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863df0368456'
down_revision = '2fc023282ae9'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa

def upgrade():
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        # Step 1: Add new column without unique constraint
        batch_op.add_column(sa.Column('new_full_name', sa.String(length=100), nullable=True))

    # Step 2: Copy data from old to new
    op.execute("UPDATE candidate SET new_full_name = full_name")

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        # Step 3: Drop old column
        batch_op.drop_column('full_name')

        # Step 4: Rename new column to original name
        batch_op.alter_column('new_full_name', new_column_name='full_name')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
