"""Add user_id to notifications

Revision ID: 87103779cc41
Revises: b3644ea1615f
Create Date: 2025-07-25 14:46:45.238468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87103779cc41'
down_revision = 'b3644ea1615f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_notifications_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
