"""Remove unique from full_name, add composite constraint

Revision ID: a14ce49d5914
Revises: 311afb43435a
Create Date: 2025-07-07 10:56:31.783136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14ce49d5914'
down_revision = '311afb43435a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_candidate_full_name'), type_='unique')
        batch_op.create_unique_constraint('unique_candidate_combination', ['user_id', 'election_id', 'position_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint('unique_candidate_combination', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_candidate_full_name'), ['full_name'])

    # ### end Alembic commands ###
