"""Add status field to Election model

Revision ID: a5cb216d74c0
Revises: b5d0d52a4d9a
Create Date: 2025-06-19 11:37:55.072129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cb216d74c0'
down_revision = 'b5d0d52a4d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', name='electionstatusenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
