"""Modify users profile images

Revision ID: b3644ea1615f
Revises: 16fe5ac3aa3b
Create Date: 2025-07-24 23:09:32.793768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3644ea1615f'
down_revision = '16fe5ac3aa3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
