"""Remove unique constraint on candidate position

Revision ID: d8237ff5d49d
Revises: 44b8222d4f73
Create Date: 2025-07-16 21:35:23.588522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8237ff5d49d'
down_revision = '44b8222d4f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_candidate_combination'), type_='unique')
        batch_op.create_unique_constraint('unique_candidate_combination', ['user_id', 'election_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint('unique_candidate_combination', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_candidate_combination'), ['user_id', 'election_id', 'position_id'])

    # ### end Alembic commands ###
