"""Add full_name, party_name, position to Candidate

Revision ID: e54a43165219
Revises: 616a96e9d822
Create Date: 2025-06-12 12:41:39.869407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54a43165219'
down_revision = '616a96e9d822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('party_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('party_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
