"""Add active field to Election

Revision ID: f18fafc1b2e7
Revises: ff8ecf1d3092
Create Date: 2025-07-13 21:06:19.658786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18fafc1b2e7'
down_revision = 'ff8ecf1d3092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_candidate_combination', ['user_id', 'election_id', 'position_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint('unique_candidate_combination', type_='unique')

    # ### end Alembic commands ###
