"""Remove start_date and end_date from Vote

Revision ID: fc9915cd0090
Revises: a6c66551c053
Create Date: 2025-09-03 21:28:07.979873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9915cd0090'
down_revision = 'a6c66551c053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
