"""Remove unique constraint on candidate full_name and election_id

Revision ID: ff8ecf1d3092
Revises: a14ce49d5914
Create Date: 2025-07-07 16:34:04.968492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8ecf1d3092'
down_revision = 'a14ce49d5914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_candidate_combination'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_candidate_combination'), ['user_id', 'election_id', 'position_id'])

    # ### end Alembic commands ###
